function listarInformes(){

	divContenidoElement.children().remove();
        divContenidoElement.append('<legend align="center">Informes solicitados últimamente</legend>'
 +'<table id="table1" class="table table-condensed" >'
 +'<thead>'
  +'<tr>'
   +'<th>#</th>'
   +'<th>Informe</th>'
   +'<th>Tipo</th>'
   +'<th>Periodo</th>'
   +'<th></th>'
   +'<th></th>'
  +'</tr>'
 +'</thead>'
 +'<tbody>'
  +'<tr class="info">'
   +'<td>1</td>'
   +'<td><a href="#">Inf040613</a></td>'
   +'<td>Mensual</td>'
   +'<td>Junio</td>'
   +'<td><i class="icon-download-alt" align="center"></i></td>'
   +'<td><i class="icon-trash" align="center"></i></td>'
  +'</tr>'
  +'<tr class="info">'
   +'<td>2</td>'
   +'<td><a href="#">Inf100713</a></td>'
   +'<td>Mensual</td>'
   +'<td>Julio</td>'
   +'<td><i class="icon-download-alt"></i></td>'
   +'<td><i class="icon-trash" align="center"></i></td>'
  +'</tr>'
  +'<tr class="info">'
   +'<td>3</td>'
   +'<td><a href="#">Inf300813</a></td>'
   +'<td>Quincenal</td>'
   +'<td>15/08 a 30/08</td>'
   +'<td><i class="icon-download-alt"></i></td>'
   +'<td><i class="icon-trash" align="center"></i></td>'
  +'</tr>'
  +'<tr class="info">'
   +'<td>4</td>'
   +'<td><a href="#">Inf150913</a></td>'
   +'<td>Quincenal</td>'
   +'<td>01/09 a 15/10</td>'
   +'<td><i class="icon-download-alt"></i></td>'
   +'<td><i class="icon-trash" align="center"></i></td>'
  +'</tr>'
 +'</tbody>'
+'</table>');

}