function realizarVenta(){

	divContenidoElement.children().remove();
 divContenidoElement.append('<form class="form-horizontal">'
              +'<fieldset>'
               +'   <legend>Vender a un cliente</legend>'

                  +'<div class="control bs-docs-example">'
                  +'<label><p><strong>Sifones a Devueltos:</strong><p></label>   '
                 
                 +' <div class="controls controls-row">'
                    +'<label class="span2" for="input01"> Tipo </label>'
                    +'<select class="span4 "id="select01">'
                    +'   <option>Ninguno</option>'
                    +'   <option>Todos</option>'
                     +'   <option>Sifon Vidrio</option>'
                        +'<option>Sifon Plastico</option>'
                        +'<option>Sifon con malla</option>'
                   +'</select>'
                   +'<label class="span2" align="left" for="input01">Canitidad</label>'
                   +'<input type="text" class="span3 input-mini" id="input01">'
                  +'</div>'
                +'</div>'
                
                 +'<div class="control bs-docs-example" id="divSifonesVender">'
                +'<div class="control">'
                  +'<label><p><strong>Sifones a Vender:</strong><p></label>   '
                  +'</div>'
                  +'<div class="controls controls-row">'
                  +'</div>'

                  +'<table id="tablaVentas" class="table table-bordered table-hover">'
                    +'<thead>'
                      +'<tr>'
                        +'<th>Tipo</th>'
              +'<th>Cantidad</th>'
              +'<th>SubTotal</th>'
            +'</tr>'
          +'</thead>'
          +'<tbody>'
            +'<tr class="info">'
              +'<td>sifones de soda</td>'
              +'<td><input id="cantidadVidrio" idSifon="" type="number" value="0" onchange="calcularSubTotal(this.value, '+SIFON_TIPO_VIDRIO+', \'vidrio_label_subtotal\');"></td>'
              +'<td><label id="vidrio_label_subtotal">0.0</label></td>'
            +'</tr>'
            +'<tr class="info">'
              +'<td></td>'
              +'<td><input id="cantidadPlastico" idSifon="" type="number" value="0" onchange="calcularSubTotal(this.value, '+SIFON_TIPO_PLASTICO+', \'plastico_label_subtotal\');"></td>'
              +'<td><label id="plastico_label_subtotal">0.0</label></td>'
            +'</tr>'
            +'<tr class="info">'
              +'<td></td>'
              +'<td><input id="cantidadMalla" idSifon="" type="number" value="0" onchange="calcularSubTotal(this.value, '+SIFON_TIPO_MALLA+', \'malla_label_subtotal\');"></td>'
              +'<td><label id="malla_label_subtotal">0.0</label></td>'
            +'</tr>'
          +'</tbody>'
                  +'</table>'

                +'</div>'
                  
 +'<div class="control-group">'
  +'<label class="span3"><p><strong> Monto a total</strong> </p></label>'
  +'<div class="span4 input-prepend input-append ">'
    +'<span class="add-on">$</span>'
      +'<input class="span4" id="montoTotal" type="text" value="0.0" readonly>'
  +'</div>'
+'</div>'

+'<div  align="center">'
+'<button type="button" id="btnVender" class="btn btn-primary" onclick="vender();" disabled="disabled">'
  +'Vender'
+'</button>'
+'</div>'
 +'           </fieldset>'
          +'</form>'
   );
// 	

}
