function verCalendario(){
	divContenidoElement.children().remove();
	divContenidoElement.append('<legend align="center">Administracion de Calendarios</legend>'
				+'<table id="table1" class="table table-bordered table-hover" >'
 				+'<thead>'
  					+'<tr>'
   						+'<th>#</th>'
   						+'<th>Dia</th>'
   						+'<th>Turno</th>'
   						+'<th>Barrios</th>'
  					+'</tr>'
 				+'</thead>'
				+'<tbody>'
  					+'<tr class="info">'
    				+'<td>1</td>'
   					+'<td><a href="detalleCliente.html">Lunes</a></td>'
   					+'<td>Mañana</td>'
   					+'<td>'
			    		+'<div class="btn-group">'
       						+'<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">'
        					+'<i class="icon-tags"></i>'
        					+'<span class="caret"></span>'
      						+'</a>'
      						+'<ul   class="dropdown-menu">'
							+'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">San Pedrito</a></li>'
      						+'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Malvinas A</a></li>'
    					+'</div>'
  					+'</tr>'
  

  					+'<tr class="info">'
    					+'<td>1</td>'
   						+'<td><a href="detalleCliente.html">Lunes</a></td>'
   						+'<td>Tarde</td>'
   						+'<td>'
    						+'<div class="btn-group">'
       						+'<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">'
        					+'<i class="icon-tags"></i>'
        					+'<span class="caret"></span>'
      						+'</a>'
      						+'<ul   class="dropdown-menu">'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Santa Rita</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">San Pedrito</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Malvinas B</a></li>'
    +'</div>'
  +'</tr>'
  

  +'<tr class="info">'
    +'<td>1</td>'
   +'<td><a href="detalleCliente.html">Martes</a></td>'
   +'<td>Mañana</td>'
   +'<td>'
    +'<div class="btn-group">'
       +'<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">'
        +'<i class="icon-tags"></i>'
        +'<span class="caret"></span>'
      +'</a>'
	      +'<ul   class="dropdown-menu">'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Santa Rita</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">San Pedrito</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Malvinas A</a></li>'
    +'</div>'
  +'</tr>'
  
  +'<tr class="info">'
    +'<td>1</td>'
   +'<td><a href="detalleCliente.html">Miercoles</a></td>'
   +'<td>Tarde</td>'
   +'<td>'
    +'<div class="btn-group">'
       +'<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">'
        +'<i class="icon-tags"></i>'
        +'<span class="caret"></span>'
      +'</a>'
      +'<ul   class="dropdown-menu">'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Santa Rita</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">San Pedrito</a></li>'
      +'<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Malvinas A</a></li>'
    +'</div>'
  +'</tr>'
  
  
  
 +'</tbody>'
+'</table>'
 
+'<div  align="center">'
+'<button class="btn btn-primary"  type="submit">'
  +'Nuevo'
+'</button>'
+'</div>');   


}

 